spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springdata
      username: root
      password: Arkadas0p
  servlet:
      multipart:
        max-file-size: 4096MB
        max-request-size: 4096MB
        enabled: true
  
server:
  servlet:
    context-path: /
  port: 8080

storage:
  location: upload-dir
  source: /Users/nguyenhoangphuc/Desktop/Video/%s.mp4

org:
  springframework:
    boot:
      autoconfigure:
        EnableAutoConfiguration: true
